apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-order-aggregator-api
  name: user-order-aggregator-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-order-aggregator-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-order-aggregator-api
    spec:
      containers:
      - image: manishkhadria/user-order-aggregator-api:0.0.2-SNAPSHOT
#        imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        name: user-order-aggregator-api
        env:
          - name: ORDER_API_URI
            value: http://order-api
          - name: USER_API_URI
            value: http://user-api
          - name: JAEGER_HOSTNAME
            value: http://jaeger-allinone
          - name: JAEGER_PORT
            value: "6831"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-order-aggregator-api
  namespace: default
  labels:
    app: user-order-aggregator-api
spec:
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
  selector:
    app: user-order-aggregator-api
#  type: ClusterIP
  type: LoadBalancer